includes/class-wc-amazon-payments-advanced-api.php

This implements the basic shipping countries setting support. More extensive support (like, limit to zipcodes) but those types of restrictions are more related to Shipping method availability and Shipping zones. 
This would require integration with external shipping methods to some extent.
The current implementation goes in line with how the list of shipping countries is populated on WooCommerce.

Implement delivery restrictions (simple and basic)

---

includes/class-wc-amazon-payments-advanced-api.php

This is in line with how WC handles this type of missconfiguration. Fixes #49

Only allow addresses within the shipping countries

---

includes/class-wc-gateway-amazon-payments-advanced.php
woocommerce-gateway-amazon-payments-advanced.php

Today on the meeting, Federico and Misha asked for 2 changes.
* When logged in, and the buyer chooses to check out with amazon, there's a checkbox that displays that prompts the user to agree to link the Amazon Pay account. This needs to default to checked, and also include a description to clarify the purpose of this option. Something like "By checking this box, every time you will log in with the same Amazon account, you will also be logged in with your existing shop account."
* When checking out as guest, and logged in on amazon, if the email exists on the database, the flow stated to send an email to verify ownership of the account. It was agreed on the call, that instead of this, we'd ask for the password, and validate the user that way.
This PR implement those changes, and bumps the …

Feedback on account matching

---

includes/class-wc-gateway-amazon-payments-advanced-subscriptions.php
includes/class-wc-gateway-amazon-payments-advanced.php
woocommerce-gateway-amazon-payments-advanced.php

Normalize and refactor URL handling.
Due to misconfiguration of some stores, where some page (checkout, cart, etc) is not configured properly, resulted in the current URL appended the query strings.
As found in WC itself [here](https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-order.php#L1639-L1644), lets default to `home_url()` with the proper trailing slash.
This will avoid the domainless situation noted in issue https://github.com/woocommerce/woocommerce-gateway-amazon-pay/issues/38
v2 will already handle this much better, and avoid Search Engines indexing the redirect URLs.

(v1) Avoid domainless redirect URLs

---

includes/admin/class-wc-amazon-payments-advanced-admin.php
includes/admin/legacy/class-wc-amazon-payments-advanced-order-admin-legacy.php
includes/class-wc-amazon-payments-advanced-api-abstract.php
includes/class-wc-gateway-amazon-payments-advanced-subscriptions.php
includes/legacy/class-wc-gateway-amazon-payments-advanced-subscriptions-legacy.php
woocommerce-gateway-amazon-payments-advanced.php

Hide buttons on subscriptions (reported by Debbie this morning right before the call).
Implements refresh button/action for CV1 billing agreements, which wasn't implemented in alpha11. This also slightly improves performance, and leaves things consistent with the rest of the CV1 functionality.
Fixes an issue where empty meta corresponding to CV2 would be created on CV1 subscriptions renewals.
Fixes the double refund issue reported by Federico, which was caused by an error in the implementation refactor done in alpha11 yesterday.
Changes copy for the "upgrade credentials" notice, as suggested by Federico after the meeting through DM.

Minor fixes before the beta

---

includes/class-wc-gateway-amazon-payments-advanced-abstract.php

The lack of a field, makes Woo think there's an empty field submitted, and therefore wipes the key.

Do not remove the keys for hidden_masked fields

---

includes/class-wc-gateway-amazon-payments-advanced.php

Quick fix for some cases on the admin where there's no WC()->cart object defined. REST API would not work and some pages will trigger a failure.

If there's not cart object (like in some admin screens) do nothing here.

---

includes/class-wc-gateway-amazon-payments-advanced.php

Fix Issue #125.
Reference ticket https://saucal.zendesk.com/agent/tickets/8358
Save Amazon Reference Id on order _transaction_id order meta field on payment process.

Set standard Transaction Id 

---

includes/class-wc-gateway-amazon-payments-advanced-subscriptions.php
includes/class-wc-gateway-amazon-payments-advanced.php

Fix issue #120
Force Decimals to 2 on amounts sent to API to prevent errors on api calls.
WooCommerce support more that 2 digit on their setting, this enables merchants to connect with some ERP systems that required this due to rounding issues.

Force Decimals to 2 on amounts sent to API

---

includes/class-wc-gateway-amazon-payments-advanced-abstract.php

This hide the API V1 keys on setting when the V2 onboarding is done.
Requested by Gerardo in Slack

Hide API V1 after onboarding is made.

---

includes/class-wc-gateway-amazon-payments-advanced-abstract.php
includes/class-wc-gateway-amazon-payments-advanced.php
woocommerce-gateway-amazon-payments-advanced.php

Fix bug we introduced in this fix https://github.com/woocommerce/woocommerce-gateway-amazon-pay/pull/127/commits/314c602df5868492ff960865e2459cb91722f54c that hides the gateway on the new installs.

Replace gateways object to avoid error on settings

---

includes/class-wc-gateway-amazon-payments-advanced.php

This fix the transaction id for the subscriptions and renewal orders, since charge_permision_id  differs to the  amazon reference id on those orders

Add correct transaction Id to subscription and renewals orders

---

includes/admin/class-wc-amazon-payments-advanced-order-admin.php
includes/class-wc-gateway-amazon-payments-advanced.php
includes/legacy/class-wc-gateway-amazon-payments-advanced-subscriptions-legacy.php

- Adds the "Invalid " label in auth_box_render.
- Checks if $charge_permission is WP_Error before trying to access props in refresh_cached_charge_permission_status
- Handles the exceptions that could be thrown from handle_generic_api_response_errors and if not catched would cause fatal errors
Closes # .
https://app.clickup.com/t/1p82xxm
https://github.com/woocommerce/woocommerce-gateway-amazon-pay/issues/115
1. Visit an order or a subscription paid using Amazon Pay that would throw an exception causing a fatal error
2. It would no longer cause an error, and the label of the billing agreement would be Invalid

fix: fatal error on Amazon API errors

---

includes/admin/class-wc-amazon-payments-advanced-order-admin.php

Avoids php warnings by checking if $charge_permission_cached_status is WP_Error before passing it to status_details_label

fix: check for wp_error before requesting status_details_label

---

includes/class-wc-gateway-amazon-payments-advanced-abstract.php
includes/class-wc-gateway-amazon-payments-advanced.php
woocommerce-gateway-amazon-payments-advanced.php

* Check if other gateways is enabled before hide checkout button issue #97
* Enable subscription amount change support Issue #106
* Accept states without letters mark variations on shipping restriction - Issue #122
* Render cart button on update shipping method
* Unify version checker
* Get order charge permission and charge id method
* Force v2 version on orders
* Remove duplicated assignation
* Add charge id for the orders with open capture
* Parse V1 ipn response to process it with V2 handler
* Skip v1 IPN handler on migration done
* Lowercase version on parsed IPN notification
* Change string replace function and save order
* Log notification Data for the V1 IPN
* Fix typos
* PHPCS issues
* PHPCS manual fixes
* PHPCS fixes
* Fix function call.
* Undo version change
* Replace gateways …

Bug Fixing (#135)

---

assets/css/style.scss
assets/js/amazon-wc-checkout.js
includes/class-wc-amazon-payments-advanced-api-abstract.php
includes/class-wc-gateway-amazon-payments-advanced-abstract.php
includes/class-wc-gateway-amazon-payments-advanced.php

Adds support for the Amazon Pay button in the WooCommerce's mini cart.
This PR should be reviewed and merged after #145.
> Add - Support for Amazon Pay in WooCommerce's mini cart.

Adds support for Amazon Pay in WooCommerce's mini cart

---

assets/css/style.scss
assets/js/amazon-wc-checkout.js
includes/class-wc-amazon-payments-advanced-api-abstract.php
includes/class-wc-gateway-amazon-payments-advanced-abstract.php
includes/class-wc-gateway-amazon-payments-advanced.php

Adds support for the Amazon Pay button in Product Pages.
Technical details
When the amazon pay button located in the product page is clicked an AJAX request is taking place which saves the active cart
in WooCommerce's session, empties current cart and adds only the selected product and finally provides the JS with required parameters for amazon to initiate the new checkout session.
When the checkout session is completed, the cart that was stored gets restored.
This PR should be reviewed and merger after #146.
> Add - Support for Amazon Pay button on Product pages.

Adds support for Amazon Pay in Product Pages

---

includes/class-wc-amazon-payments-adavanced-alexa-notifications-abstract.php
includes/class-wc-amazon-payments-advanced-alexa-notifications.php
includes/class-wc-amazon-payments-advanced-api-abstract.php
includes/class-wc-amazon-payments-advanced-api.php
includes/class-wc-gateway-amazon-payments-advanced-abstract.php
woocommerce-gateway-amazon-payments-advanced.php

Adds support for Alexa Delivery Notifications. Shipping plugins can simply call
`do_action( 'apa_enable_alexa_notifications', $tracking_number, $carrier, $order_id );`
in a time where wc_get_order is applicable to be called, and as long as the merchant has enabled the corresponding option, alexa delivery notifications will be enabled for the $order_id.
> Add - Support for Alexa Delivery Notifications

Adds support for Alexa Delivery notifications

---

includes/class-wc-gateway-amazon-payments-advanced.php

Seemed to me like there was no point in checking individual for each of the features added the availability.
Seems simpler and better to only remove false when there is a blocker, if there isn't we can safely remove true.
Solves https://app.clickup.com/t/23uzt21

removes individual feature checking for availability

---

includes/class-wc-gateway-amazon-payments-advanced.php

As it was, the code would overwrite anything added in the paymentDetails offset through filters. That was including the support for multicurrency in the EU/GB regions.
solves https://app.clickup.com/t/25enzm6

don't overwrite completely filtered paymentDetails offset

---

assets/css/style.scss
includes/class-wc-gateway-amazon-payments-advanced.php

Adds the amazon pay button to a container following WooCommerce's paddings.
Solves https://app.clickup.com/t/2a7r4pm

fixes margins in mini-cart Amazon Pay button

---

assets/js/amazon-wc-checkout.js

Render Amazon Pay Buttons even if they are not :visible. Don't render them only if the target button has id `#pay_with_amazon` for backwards compatibility.
1. Prior to this, Amazon Button in the mini cart would only render if it was :visible
2. No it should render even if its not.
No need for changelog entry, since the issue hasn't been introduced yet in the production version of the plugin.

renders newers amazon buttons even if they are hidden

---

assets/js/amazon-wc-checkout.js

Was introduced in pull #165 and produces:
```
Uncaught AmazonPay:
Can not find element #pay_with_amazon_2 for amazon.Pay.renderButton.
```
renderButton is being registered as a callback to jQuery Events, which pass always the Event as the first parameter. As a result the function was running with invalid parameters. We ensure that when that happens, params revert back to defaults.

prevents JS fatal when jQuery.Event is passed to renderButton

---

includes/class-wc-gateway-amazon-payments-advanced.php

When checking for Gateway's availability, do not update plugin's validation flag. This flag is being updated while on the backend.
The issue came up from the way this flag was being updated. 
1. Fresh install of amazon pay plugin shouldn't exhaust memory.
> Fix - Infinite Loop causing Memory Exhaustion.

Fixes infinite loop exhausting memory

---

includes/class-wc-gateway-amazon-payments-advanced.php

Fixes a warning for single products
1. Warning shouldn;t appear on Single product regarding the 'subscriptions_enabled' not being set

fix warning on single products

---

src/payments-methods/express/payment-methods-express.js
src/renderAmazonButton.js

Listening for changes on the total amount for the checkout and/or the currency code. If that happens using the Components key attribute, we force a remount and render the new Amazon Pay button using the updated estimatedOrderAmount value.
1. Estimated order amount should get updated after the checkout total is changed in cart and checkout blocks

Updated estimated order amount on total change for blocks

---

.gitattributes
assets/js/amazon-wc-admin.js
composer.json
includes/admin/class-wc-amazon-payments-advanced-admin.php
includes/admin/class-wc-amazon-payments-advanced-order-admin.php
includes/admin/legacy/class-wc-amazon-payments-advanced-order-admin-legacy.php
includes/class-wc-amazon-payments-advanced-rest-api-controller.php
includes/class-wc-amazon-payments-advanced-utils.php
includes/class-wc-gateway-amazon-payments-advanced-privacy.php
includes/legacy/class-wc-amazon-payments-advanced-api-legacy.php
includes/legacy/class-wc-amazon-payments-advanced-ipn-handler-legacy.php
includes/legacy/class-wc-gateway-amazon-payments-advanced-legacy.php
includes/legacy/class-wc-gateway-amazon-payments-advanced-subscriptions-legacy.php
package.json
woocommerce-gateway-amazon-payments-advanced.php

Making Amazon Pay plugin compatible with HPOS
Made the plugin compatible using this [guide](https://github.com/woocommerce/woocommerce/wiki/High-Performance-Order-Storage-Upgrade-Recipe-Book#declaring-extension-incompatibility)
Skipped:
- includes/compats/class-wc-amazon-payments-advanced-multi-currency-abstract.php L215-216
Closes woo#226 .
1. [Enable](https://github.com/woocommerce/woocommerce/wiki/High-Performance-Order-Storage-Upgrade-Recipe-Book#how-to-enable-hpos) HPOS in your installation.
2. Plugins functionality should remain the same regardless of HPOS unless you are using legacy API Keys
> ADD - Compatibility with HPOS

Making Plugin compatible with HPOS

---

.gitattributes
includes/class-wc-amazon-payments-advanced-compat.php
includes/compats/woo-blocks/class-wc-amazon-payments-advanced-block-compat-express.php
src/utils.js
woocommerce-gateway-amazon-payments-advanced.php

We won't load the Express Gateway for merchants not yet migrated to V2 Amazon Keys and the FE is going to reflect that.
Closes woo#225 .
1. While using V2 keys of Amazon and WooCommerce Blocks, Amazon Express should appear in the cart and checkout blocks.
2. While using V1 keys of Amazon and WooCommerce Blocks, Amazon Express shoud not appear in the cart and checkout blocks.
3. WHile using V1 keys of Amazon and WooCommerce Blocks, classic gateway should not be present.
4. While using V1 keys of Amazon and WooCommerce Blocks, no error should be thrown.
> Fix - Error for merchants still using V1 Amazon Keys

Fixes error for merchants not yet migrated to v2 amazon keys

---

includes/compats/woo-blocks/class-wc-amazon-payments-advanced-block-compat-abstract.php
includes/compats/woo-blocks/class-wc-amazon-payments-advanced-block-compat-classic.php
includes/compats/woo-blocks/class-wc-amazon-payments-advanced-block-compat-express.php

FE provided allowed currencies to blocks should take into consideration if there is a multi currency plugin enabled. Also altered PHP to return false instead of an empty array when there should be the selected currency available when no multi currency plugin is present.
1. Amazon Pay Express should be enabled when no compatible multicurrency plugin is present when using blocks.
2. If a mutli currency compatible plugin is disabled, FE allowed currencies should be just like if that plugin was never part of the installation when using blocks.
3. If a disallowed currency is selected amazon pay Express should be unavailable when using blocks.
> FIX -

Fix fe provided allowed currencies, if multi currency disabled

---

includes/class-wc-amazon-payments-advanced-alexa-notifications.php

1. In sandobx mode you can in your code the below:
`do_action( 'woocommerce_amazon_pa_enable_alexa_notifications', 'ANYTHING_AS_TRACKING_NUMBER', 'VALID_AMAZON_CARRIER_CODE', (int) VALID_ORDER_ID_PAYED_WITH_AMAZON );`
You can find a list of valid amazon carrier codes [here](https://developer.amazon.com/docs/amazon-pay-checkout/setting-up-delivery-notifications.html)
2. You should see an entry in the amazon log under woocommerce > status > logs about the result of the delivery notification
3. The alexa delivery notification request should return a 200 status response to be succesful
> FIX - Alexa delivery notification request format

fix alexa's request format

---

includes/class-wc-gateway-amazon-payments-advanced.php
tests/phpunit/includes/test-wc-gateway-amazon-payments-advanced.php

Closes woo#251 .
1. Enable the Amazon Pay for single product pages from the plugin's options
2. Set a product to in stock or backorder. The Amazon pay button should appear.
3. Set the product as out of stock. The product should dissappear and Amazon pay related scripts should not be loaded in the page.
> Fix - Amazon pay button should appear on single product page only when the product is purchasable and in stock.

Fix the button on single product page to appear only when applicable

---

includes/admin/class-wc-amazon-payments-advanced-admin.php

In the plugin's setting page a review prompt is being added. The prompt has 3 links.
1) To the review page
2) To dismiss the prompt
3) To the support page
When this feature is released, the plugin will store 2 dates in the DB on the first admin request. The date of the installation/activation/update of the plugin including this feature (anniversary date). The date of the anniversary date + 1 month in the future (hidden_until_date).
When the actual date becomes > than the hidden until date, the review prompt will appear in the plugin's settings page.
When the user clicks the dismiss link of the prompt, the prompt will remain hidden until the next anniversary date arrives.
Option keys:
`amazon_payments_advanced_anniversary_date`
`amazon_payments_advanced_hidden_until_date`
1. The review …

Reviews prompt

---

includes/class-wc-gateway-amazon-payments-advanced-abstract.php
includes/class-wc-gateway-amazon-payments-advanced.php
includes/legacy/class-wc-gateway-amazon-payments-advanced-legacy.php

1. Install a build version of this branch.
2. Enable the button on the mini-cart and the option Hide Button Mode.
3. The -- OR -- separator shouldn't be visible in the minicart.
> Fix - Button separator displayed on the mini-cart when it shouldn't.

do not display the separator on minicart if button should be hidden

---

includes/class-wc-amazon-payments-advanced-api-abstract.php
includes/class-wc-gateway-amazon-payments-advanced-subscriptions.php
includes/class-wc-gateway-amazon-payments-advanced.php
woocommerce-gateway-amazon-payments-advanced.php

Rel card: https://app.clickup.com/t/860qe8m2e
1. Install a built of this PR and the Price Based on Country plugin (free version)
2. Add Japan with JPY currency in the Price Based on Country plugin.
3. A customer with shipping address on Japan should be able to complete the checkout.
> Fix - Checkout error with JPY currency and decimals set to non 0.

Force decimals with JPY always to be 0

---

readme.txt
woocommerce-gateway-amazon-payments-advanced.php

Change PluginName from: **WooCommerce Amazon Pay**, To: **Amazon Pay for WooCommerce**
Closes: https://app.clickup.com/t/86dv9pzka
1. Check plugin name
2. Should be: Amazon Pay for WooCommerce
The plugin name has been changed

Change the Plugin's Name in the WP plugin directory

---

includes/class-wc-gateway-amazon-payments-advanced-abstract.php
includes/compats/woo-blocks/class-wc-amazon-payments-advanced-block-compat-abstract.php
includes/compats/woo-blocks/class-wc-amazon-payments-advanced-block-compat-express.php
package-lock.json
src/js/_utils.js
src/js/payments-methods/express/_payment-methods.js
src/js/payments-methods/express/index.js

Prevents the users from editing their address on the Checkout block after they are logged in to Amazon.
1. Configure the Checkout using the block, not the legacy shortcode.
2. Navigate to the checkout page and log in using the Amazon Express button
3. The address should not be editable.
- Prevent address editing when user is logged with Amazon Express (Checkout Blocks)

disable editing the address if the user is logged in

---

includes/class-wc-amazon-payments-advanced-api-abstract.php
includes/class-wc-gateway-amazon-payments-advanced.php

Ensure that the order's address matches with the address in the Amazon checkout session.
1. Add a product to the cart and navigate to the checkout page.
2. Duplicate the checkout tab in your browser.
3. Initiate the classic checkout process in Tab 1 but don't complete the payment yet.
4. Update the address in the checkout in Tab 2.
5. Complete the payment in Tab 1.
6. The address in WooCommerce's backend should match with the Amazon seller central.
> Prevent address mismatch between WooCommerce and Amazon Seller Central.

update order address to match the checkout session

---

includes/class-wc-gateway-amazon-payments-advanced.php

---
This PR updates the `validate_session_properties()` method to gracefully skip over invalid or undefined keys in the `$current` array during validation, rather than throwing a PHP warning or failing the entire validation process.
Specifically, it avoids validating keys from `$desired` that do not exist in `$current` (such as `"--"`), by adding an `isset()` check and using `continue` to proceed with the next item in the loop.
Closes #306
---
1. Trigger an Amazon Pay checkout session using WooCommerce with the Amazon Gateway plugin.
2. Log a case where the API returns unexpected keys like `"--"` in the payload.
3. Confirm that no PHP warnings like `Undefined array key "--"` are logged, and that other session properties still validate correctly.
---
---
> Fix – Skip undefined array keys …

Validate array session
