saucal/woocommerce-gateway-amazon-pay

includes/class-wc-amazon-payments-advanced-api-abstract.php
includes/class-wc-amazon-payments-advanced-api.php
includes/class-wc-gateway-amazon-payments-advanced.php
includes/legacy/class-wc-amazon-payments-advanced-api.php
package.json
woocommerce-gateway-amazon-payments-advanced.php

Some fixes and changes captured while onboarding the codebase

General fixes

---

assets/js/amazon-wc-admin.js
includes/class-wc-gateway-amazon-payments-advanced.php
woocommerce-gateway-amazon-payments-advanced.php

Feedback on this card https://app.breeze.pm/projects/148278/cards/3593211

Changes on wording and functionality based on feedback.

---

assets/js/amazon-wc-admin.js
includes/class-wc-amazon-payments-advanced-api.php
includes/class-wc-gateway-amazon-payments-advanced.php
includes/legacy/class-wc-amazon-payments-advanced-api-legacy.php
woocommerce-gateway-amazon-payments-advanced.php

This PR handles the import changes requested on previous review calls. Improves the manual import process to make it more streamlined.
Related card: https://app.breeze.pm/projects/148278/cards/3591583

Replace paste keys with import

---

assets/js/amazon-wc-admin.js
includes/admin/class-wc-amazon-payments-advanced-admin.php
includes/class-wc-amazon-payments-advanced-api.php
includes/class-wc-gateway-amazon-payments-advanced-abstract.php

Fix some issues reported on a full QA pass on the plugin.

Fix several issues

---

assets/js/amazon-wc-admin.js
assets/js/amazon-wc-checkout.js
includes/admin/class-wc-amazon-payments-advanced-admin.php
includes/class-wc-amazon-payments-advanced-api-abstract.php
includes/class-wc-amazon-payments-advanced-api.php
includes/class-wc-amazon-payments-advanced-merchant-onboarding-handler.php
includes/class-wc-gateway-amazon-payments-advanced-abstract.php
includes/class-wc-gateway-amazon-payments-advanced-subscriptions.php
includes/class-wc-gateway-amazon-payments-advanced.php
woocommerce-gateway-amazon-payments-advanced.php

Tackle some feedback from Amazon, and some further cleanup.

Customer Feedback and Cleanup

---

assets/js/amazon-wc-checkout.js
includes/class-wc-amazon-payments-advanced-api.php
includes/class-wc-amazon-payments-advanced-ipn-handler-abstract.php
includes/class-wc-amazon-payments-advanced-ipn-handler.php
includes/class-wc-gateway-amazon-payments-advanced.php
includes/legacy/class-wc-amazon-payments-advanced-ipn-handler-legacy.php
woocommerce-gateway-amazon-payments-advanced.php

This allows authorization flows to happen through IPNs and cron polling mechanisms.

Authorize flow and basic IPN handling

---

includes/class-wc-gateway-amazon-payments-advanced-abstract.php
includes/class-wc-gateway-amazon-payments-advanced-subscriptions.php
includes/class-wc-gateway-amazon-payments-advanced.php
woocommerce-gateway-amazon-payments-advanced.php

This PR basically disables the order pay screen (known to be broken) and subscription support.

Disable specific features for an alpha release

---

includes/class-wc-amazon-payments-advanced-api.php

Set proper platformId

---

assets/js/amazon-wc-admin.js
includes/class-wc-gateway-amazon-payments-advanced-abstract.php
woocommerce-gateway-amazon-payments-advanced.php

This includes some UX fixes on the admin screens

alpha5 release

---

includes/class-wc-amazon-payments-advanced-api.php
includes/class-wc-amazon-payments-advanced-ipn-handler.php
includes/class-wc-gateway-amazon-payments-advanced.php
woocommerce-gateway-amazon-payments-advanced.php

Implement several things to improve logging across the plugin.

Improve logging

---

includes/class-wc-gateway-amazon-payments-advanced-subscriptions.php
includes/class-wc-gateway-amazon-payments-advanced.php
woocommerce-gateway-amazon-payments-advanced.php

Reverts saucal/woocommerce-gateway-amazon-pay#60

Revert "(v1) Avoid domainless redirect URLs"

---

assets/css/style.scss
assets/js/amazon-wc-checkout.js
includes/class-wc-gateway-amazon-payments-advanced.php

Fixes hide button setting not working

---

assets/css/style.scss
includes/admin/class-wc-amazon-payments-advanced-order-admin.php
includes/class-wc-amazon-payments-advanced-api.php
includes/class-wc-gateway-amazon-payments-advanced-subscriptions.php
includes/class-wc-gateway-amazon-payments-advanced.php
woocommerce-gateway-amazon-payments-advanced.php

This finishes the alpha8 release of the plugin, which includes multicurrency and subscription fixes.

Subscription functionality fixes

---

includes/class-wc-amazon-payments-advanced-api-abstract.php
includes/class-wc-gateway-amazon-payments-advanced-subscriptions.php
includes/class-wc-gateway-amazon-payments-advanced.php
includes/compats/class-wc-amazon-payments-advanced-multi-currency.php
woocommerce-gateway-amazon-payments-advanced.php

Major fixes to keep moving forward. Code actually submitted by Laura.

Several fixes

---

composer.json
includes/class-wc-amazon-payments-advanced-api-abstract.php
includes/class-wc-gateway-amazon-payments-advanced-subscriptions.php
includes/class-wc-gateway-amazon-payments-advanced.php
includes/legacy/class-wc-gateway-amazon-payments-advanced-legacy.php
includes/legacy/class-wc-gateway-amazon-payments-advanced-subscriptions-legacy.php
woocommerce-gateway-amazon-payments-advanced.php

This fixes some of the implementations done in alpha9, and also some migration issues reported by the Amazon team.

Various fixes

---

includes/admin/class-wc-amazon-payments-advanced-order-admin.php
includes/class-wc-amazon-payments-advanced-rest-api-controller.php
includes/class-wc-gateway-amazon-payments-advanced.php

Rearrange REST API class, and make it work for v2 orders, as seamlessly as possible.

Implement REST API integration for v2 orders

---

includes/class-wc-gateway-amazon-payments-advanced-privacy.php

The privacy class handles the export and scrub of amazon related data.
On this PR, i've fixed some issues i've found with the v1 implementation, and added the v2 data.

Refactor the privacy class to work with v2

---

includes/admin/class-wc-amazon-payments-advanced-order-admin.php
includes/admin/legacy/class-wc-amazon-payments-advanced-order-admin-legacy.php
includes/class-wc-amazon-payments-advanced-ipn-handler.php
includes/class-wc-amazon-payments-advanced-merchant-onboarding-handler.php
includes/class-wc-gateway-amazon-payments-advanced-privacy.php
includes/class-wc-gateway-amazon-payments-advanced-subscriptions.php
includes/class-wc-gateway-amazon-payments-advanced.php
includes/legacy/class-wc-amazon-payments-advanced-api-legacy.php
includes/legacy/class-wc-gateway-amazon-payments-advanced-subscriptions-legacy.php
phpcs.xml
templates/emails/legacy/hard-decline.php
templates/emails/legacy/soft-decline.php

There were some coding standards that were disabled before, lets fix them or address them properly.

Fix some remaining coding standards

---

includes/class-wc-amazon-payments-advanced-ipn-handler.php
includes/class-wc-gateway-amazon-payments-advanced-subscriptions.php
includes/class-wc-gateway-amazon-payments-advanced.php
includes/legacy/class-wc-amazon-payments-advanced-api-legacy.php

Remove finished TODOs and do some of them as well.

General cleanup

---

composer.json
composer.lock
includes/admin/class-wc-amazon-payments-advanced-admin.php
includes/class-wc-amazon-payments-advanced-api-abstract.php
includes/class-wc-amazon-payments-advanced-ipn-handler.php
includes/class-wc-amazon-payments-advanced-merchant-onboarding-handler.php
includes/class-wc-amazon-payments-advanced-rest-api-controller.php
includes/class-wc-gateway-amazon-payments-advanced-abstract.php
includes/class-wc-gateway-amazon-payments-advanced-subscriptions.php
includes/class-wc-gateway-amazon-payments-advanced.php
includes/legacy/class-wc-amazon-payments-advanced-api-legacy.php
phpstan.neon
woocommerce-gateway-amazon-payments-advanced.php

By using PHPStan I was able to detect a few more errors with data documentation.

PHPStan Pass

---

includes/class-wc-gateway-amazon-payments-advanced.php
includes/compats/class-wc-amazon-payments-advanced-multi-currency-abstract.php
includes/compats/class-wc-amazon-payments-advanced-multi-currency-wpml.php

Fixes #86
Fixes #88
Fixes #94
Fixes #95

Fixes several issues

---

composer.lock
includes/class-wc-amazon-payments-advanced-api.php
includes/class-wc-gateway-amazon-payments-advanced-abstract.php

Fixed some issues uncovered on a security audit performed by Amazon on the plugin.
Basically:
* Removes the import/export functionality as it exposes private keys.
* Removes secrets from being exposed in the HTML.
* Removes sensitive customer data from the logs.
* Update dependencies.

Fix issues from security audit

---

assets/js/amazon-wc-admin.js
includes/admin/class-wc-amazon-payments-advanced-admin.php
includes/class-wc-amazon-payments-advanced-api-abstract.php
includes/class-wc-amazon-payments-advanced-api.php
includes/class-wc-gateway-amazon-payments-advanced-abstract.php

This allows merchants that have the issue, to find their keys again, and re enter them.

Allow merchants to fix issue with corrupted CV1 keys

---

includes/class-wc-gateway-amazon-payments-advanced.php

Properly compare numeric arrays, to avoid some issues.

Fix issue when shipping states are limited, and comparison fails.

---

includes/class-wc-amazon-payments-advanced-api.php

Fixes issues with shipping zone configurations (mainly reported in the US, but affects anywhere where state level limitations can be set).

When a country is allowed fully somewhere, means that we allow that region fully.

---

includes/class-wc-gateway-amazon-payments-advanced-abstract.php
includes/class-wc-gateway-amazon-payments-advanced.php

Closes # .
1.
2.
3.
> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

Check if other gateways is enabled before hide checkout button issue #97

---

includes/class-wc-gateway-amazon-payments-advanced-subscriptions.php

Closes # .
1.
2.
3.
> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

Enable subscription amount change support

---

assets/js/amazon-wc-checkout.js

Closes #126.
1. Set a shipping zone with more than one shipping method
2. Add a product to Cart
3. Switch shipping method in cart, amazon button should remain.
> Fix cart Amazon Pay button render on shipping method change

Render cart button on update shipping method

---

includes/class-wc-amazon-payments-advanced-api.php
includes/class-wc-gateway-amazon-payments-advanced-abstract.php

Fix some issues that got past our previous PRs

Fix coding standards issues

---

changelog.txt
package-lock.json
package.json
readme.txt
woocommerce-gateway-amazon-payments-advanced.php

Rebasing, to be able to start branches from an updated branch.

Rebase our main branch from woo's main branch

---

includes/class-wc-gateway-amazon-payments-advanced-abstract.php
includes/class-wc-gateway-amazon-payments-advanced.php

Setting the $is_available to true when is_checkout_pay_page() was true was a bug. The $is_available variable should only be altered to false without checking prior rules.
Also introduces the is_available method for all the available button placements.
> Fix - is_available method would return true even when region would not support currency.
> Fix - Passes all the button placement through the is_available gateway method.

fixes is_available and checks availability for all button placements

---

package.json

https://github.com/npm/cli/blob/latest/changelogs/CHANGELOG-7.md#all-lifecycle-scripts

rename assets node to config. 

---

includes/class-wc-gateway-amazon-payments-advanced-subscriptions.php
includes/class-wc-gateway-amazon-payments-advanced.php
src/payments-methods/classic/payment-methods.js

Closes https://app.clickup.com/t/258rpda .
>Fix - Makes a phone field to be submitted required when using Amazon Pay "Classic"

required a phone to be submitted when using amazon classic

---

includes/class-wc-gateway-amazon-payments-advanced.php

Honors the plugin option for subscriptions support. Also moves an action to be declared earlier since there were some inconsistencies. 
solves https://app.clickup.com/t/25eh66z

honor plugins sub support and declare an action earlier

---

includes/class-wc-amazon-payments-advanced-alexa-notifications.php
includes/class-wc-amazon-payments-advanced-api.php
includes/class-wc-gateway-amazon-payments-advanced-abstract.php
includes/class-wc-gateway-amazon-payments-advanced-subscriptions.php
includes/class-wc-gateway-amazon-payments-advanced.php
includes/legacy/class-wc-gateway-amazon-payments-advanced-subscriptions-legacy.php

Follows naming conventions on actions and filters and correctly registers an action for non logged in users too.

adjusts according to naming convections / fixes typo

---

assets/js/amazon-wc-checkout.js

Refreshes Amazon Pay mini cart button on the wc_fragments_refreshed additionally.

refresh mini cart Amazon Pay button on wc_fragments_refreshed too

---

includes/class-wc-gateway-amazon-payments-advanced.php

Closes woo#233 .
1. After receiving an IPN of a canceled charge the order should update to pending instead of on-hold or if its canceled already its status should not change.
> Fix : Order status update after receiving a canceled charge through IPN

apply changes suggested by issue #233

---

composer.json
composer.lock
includes/class-wc-amazon-payments-advanced-api-abstract.php
includes/class-wc-amazon-payments-advanced-api.php

Reverts saucal/woocommerce-gateway-amazon-pay#206

Revert "Tweak/plugin header updates"

---

includes/class-wc-amazon-payments-advanced-api-abstract.php
includes/class-wc-gateway-amazon-payments-advanced-abstract.php
includes/class-wc-gateway-amazon-payments-advanced.php
includes/legacy/class-wc-gateway-amazon-payments-advanced-legacy.php
tests/e2e/lib/store-owner-flow.js
tests/e2e/lib/wp-admin-wc-settings-checkout-amazon-pay.js
tests/phpunit/includes/test-wc-amazon-payments-advanced-api.php

Remove the setting "Hide standard checkout button" because it may be too intrusive.
1. Install a built of this PR.
2. The setting "Hide standard checkout button" should not be displayed.
> Update - Remove the setting "Hide standard checkout button"

Remove hide standard checkout button setting

---

composer.lock

Update composer versions since tests are failing because the Polyfills.
1. Tests are failing with other PRs, should work with after merging this one.

Update composer packages - polyfills required

---

woocommerce-gateway-amazon-payments-advanced.php

https://app.clickup.com/t/86dtxd4g8

Prevent bail of API routes

---

includes/class-wc-gateway-amazon-payments-advanced-abstract.php

Closes # .
1.
2.
3.
> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

Add onboarding links text

---

src/js/payments-methods/classic/_payment-methods.js
src/js/payments-methods/express/_payment-methods-express.js

Closes: https://app.clickup.com/t/86dvwpdx1
1.Update to WooCommerce 9.6.0 and change Cart and Checkout to blocks
2. Go to site add any product to cart and go to Cart or Checkout page. See the warnings
> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

Replace onCheckoutAfterProcessingWithSuccess and onPaymentProcessing
